### ISSUE TITLE
consider replacing demo.gif with an URI?

### ISSUE THREAD

**Issue by haolian9** [ii14/neorepl.nvim#16]
Hi, I just found this interesting plugin, nice job!
I just noticed `/media/demo.gif` takes 8M storage, that's too big for a source code project IMO.
Would you consider replacing it with an URI?
If may have no big difference in reducing the total size of this project since the image has already be included in the git object database, but if users obtain it via `git clone --depth 1`, this would still be worth to do.

**Comment by haolian9** [comment]
i uploaded it here: https://user-images.githubusercontent.com/6236829/200223691-54c6994e-0a6b-4427-933a-86e7317f6da8.png
![screenshot](https://user-images.githubusercontent.com/6236829/200223691-54c6994e-0a6b-4427-933a-86e7317f6da8.png)

(this issue reminds me one of my project requires 100+M dataset, hehe)

**Comment by ii14** [comment]
![demo](https://user-images.githubusercontent.com/59243201/200236872-97304492-6b4c-4de5-9cad-f530ce5eab3d.gif)
