### ISSUE TITLE
REPL  in terminal mode?

### ISSUE THREAD

**Issue by lytex** [ii14/neorepl.nvim#22]
I'm using this plugin as kind of a terminal, and the fact that is in insert/normal mode tripped me off, since I was expecting C-w k to move outside of the repl (like when the buffer is in terminal mode) but instead it deletes a word (since the buffer is in insert mode)

What do you think?

**Comment by ii14** [comment]
Is `Ctrl-W` a default terminal mapping in neovim now? I know vim's terminal emulator has that mapping, but in neovim it used to be just `Ctrl-\ Ctrl-O` to run a normal mode command. Are you sure it's not your own custom mapping? You can add your custom key mappings in `ftplugin/neorepl.{vim,lua}` script.

As much as it would be possible to use a terminal buffer, it's a lot of work for questionable benefit. You have to essentially write a full terminal "application" with its own state, rendering and key handling (inside neovim process, in lua, but still). Also inheriting highlights, custom mappings and everything else you'd expect to just work would have to be implemented and maintained. And I like that normal mode editing just works, for free.

You should be able to get the behavior closer to terminal mode by scripting neorepl ftplugin. Like adding the mentioned key mappings and entering insert mode by default.

**Comment by lytex** [comment]
> Is `Ctrl-W` a default terminal mapping in neovim now? I know vim's terminal emulator has that mapping, but in neovim it used to be just `Ctrl-\ Ctrl-O` to run a normal mode command. Are you sure it's not your own custom mapping? You can add your custom key mappings in `ftplugin/neorepl.{vim,lua}` script.

No, it is not. I have `nnoremap <C-w> <C-\><C-n><C-w>` set on my config.

> You should be able to get the behavior closer to terminal mode by scripting neorepl ftplugin. Like adding the mentioned key mappings and entering insert mode by default.

Will do that, thanks!
